const response = (description, schema = { $ref: '#/components/schemas/SuccessResponse' }) => ({ description, content: { 'application/json': { schema, example: { success: true, data: {} } } } });
const error = { description: 'Validation, authentication, or not-found error', content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' }, example: { success: false, message: 'Product not found' } } } };
const jsonBody = (schema, example) => ({ required: true, content: { 'application/json': { schema: { $ref: `#/components/schemas/${schema}` }, example } } });
const auth = [{ bearerAuth: [] }];
const op = (summary, responses = { 200: response('Successful response'), 400: error }, security) => ({ summary, tags: ['E-commerce API'], ...(security ? { security } : {}), responses });

export default {
  openapi: '3.0.3', info: { title: 'E-commerce REST API', version: '1.0.0', description: 'SQLite-backed local e-commerce API. The Try it out button works against the running API.' }, servers: [{ url: '/' }],
  tags: [{ name: 'E-commerce API' }],
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
    schemas: {
      SuccessResponse: { type: 'object', properties: { success: { type: 'boolean', example: true }, data: {} } }, ErrorResponse: { type: 'object', required: ['success', 'message'], properties: { success: { type: 'boolean', example: false }, message: { type: 'string', example: 'Validation error' } } },
      Register: { type: 'object', required: ['name', 'email', 'password'], properties: { name: { type: 'string' }, email: { type: 'string', format: 'email' }, password: { type: 'string', minLength: 6 } } }, Login: { type: 'object', required: ['email', 'password'], properties: { email: { type: 'string', format: 'email' }, password: { type: 'string' } } },
      Product: { type: 'object', required: ['name', 'price'], properties: { id: { type: 'integer' }, name: { type: 'string' }, description: { type: 'string' }, price: { type: 'number', minimum: 0 }, stock: { type: 'integer', minimum: 0 }, category_id: { type: 'integer', nullable: true }, image_url: { type: 'string', nullable: true } } }, Category: { type: 'object', required: ['name'], properties: { id: { type: 'integer' }, name: { type: 'string' }, description: { type: 'string' } } },
      UserUpdate: { type: 'object', properties: { name: { type: 'string' }, email: { type: 'string', format: 'email' }, password: { type: 'string', minLength: 6 }, role: { type: 'string', enum: ['customer', 'admin'] } } }, CartItem: { type: 'object', required: ['product_id', 'quantity'], properties: { product_id: { type: 'integer' }, quantity: { type: 'integer', minimum: 1 } } },
      Order: { type: 'object', properties: { id: { type: 'integer' }, status: { type: 'string' }, total: { type: 'number' }, items: { type: 'array', items: { type: 'object' } } } }, Rating: { type: 'object', required: ['product_id', 'rating'], properties: { product_id: { type: 'integer' }, rating: { type: 'integer', minimum: 1, maximum: 5 }, review: { type: 'string' } } }, Contact: { type: 'object', required: ['name', 'email', 'phone', 'subject', 'message'], properties: { name: { type: 'string' }, email: { type: 'string', format: 'email' }, phone: { type: 'string', example: '+8801611112222' }, subject: { type: 'string' }, message: { type: 'string' } } }
    }
  },
  paths: {
    '/': { get: op('API homepage') },
    '/api/auth/register': { post: { ...op('Register a customer', { 201: response('User and JWT token'), 400: error, 409: error }), requestBody: jsonBody('Register', { name: 'Jane Doe', email: 'jane@example.com', password: 'secret123' }) } },
    '/api/auth/login': { post: { ...op('Log in and receive a JWT', { 200: response('User and JWT token'), 401: error }), requestBody: jsonBody('Login', { email: 'jane@example.com', password: 'secret123' }) } },
    '/api/auth/me': { get: op('Get current user', { 200: response('Current user'), 401: error }, auth) },
    '/api/users/{id}': { get: op('Get a user profile', undefined, auth), put: { ...op('Update a user profile', undefined, auth), requestBody: jsonBody('UserUpdate', { name: 'Jane Updated' }) }, delete: op('Delete a user', undefined, auth) },
    '/api/products': { get: { ...op('List, search, filter, and sort products'), parameters: [{ in: 'query', name: 'search', schema: { type: 'string' } }, { in: 'query', name: 'category_id', schema: { type: 'integer' } }, { in: 'query', name: 'min_price', schema: { type: 'number' } }, { in: 'query', name: 'max_price', schema: { type: 'number' } }, { in: 'query', name: 'sort', schema: { type: 'string', enum: ['newest', 'price_asc', 'price_desc'] } }] }, post: { ...op('Create product', undefined, auth), requestBody: jsonBody('Product', { name: 'T-shirt', price: 29.99, stock: 10 }) } },
    '/api/products/{id}': { get: op('Get product'), put: { ...op('Update product', undefined, auth), requestBody: jsonBody('Product', { price: 24.99 }) }, delete: op('Delete product', undefined, auth) },
    '/api/categories': { get: op('List categories'), post: { ...op('Create category', undefined, auth), requestBody: jsonBody('Category', { name: 'Clothing' }) } }, '/api/categories/{id}': { get: op('Get category'), put: { ...op('Update category', undefined, auth), requestBody: jsonBody('Category', { name: 'Apparel' }) }, delete: op('Delete category', undefined, auth) },
    '/api/cart': { get: op('Get current user cart', undefined, auth), post: { ...op('Add item to cart', undefined, auth), requestBody: jsonBody('CartItem', { product_id: 1, quantity: 2 }) }, delete: op('Clear current user cart', undefined, auth) }, '/api/cart/{productId}': { put: { ...op('Change cart item quantity', undefined, auth), requestBody: jsonBody('CartItem', { quantity: 3 }) }, delete: op('Remove cart item', undefined, auth) },
    '/api/orders': { get: op('List current user orders or all orders for admin', undefined, auth), post: op('Create order from current cart', { 201: response('Created order'), 400: error }, auth) }, '/api/orders/{id}': { get: op('Get an order', undefined, auth) }, '/api/orders/{id}/status': { put: { ...op('Update order status (admin)', undefined, auth), requestBody: { content: { 'application/json': { schema: { type: 'object', properties: { status: { type: 'string' } } }, example: { status: 'shipped' } } } } } }, '/api/orders/{id}/cancel': { post: op('Cancel a pending, paid, or processing order', undefined, auth) },
    '/api/ratings/{productId}': { get: op('List product ratings') }, '/api/ratings': { post: { ...op('Create product rating', undefined, auth), requestBody: jsonBody('Rating', { product_id: 1, rating: 5, review: 'Excellent' }) } }, '/api/ratings/{id}': { put: { ...op('Update rating', undefined, auth), requestBody: jsonBody('Rating', { rating: 4, review: 'Good' }) }, delete: op('Delete rating', undefined, auth) },
    '/api/contact': { post: { ...op('Send contact email', { 202: response('Message accepted'), 400: error, 503: error }), requestBody: jsonBody('Contact', { name: 'Jane Doe', email: 'jane@example.com', phone: '+8801611112222', subject: 'Question', message: 'Hello!' }) } }
  }
};